In [44]:
!pip install pycoingecko

Requirement already satisfied: pycoingecko in D:\ml\.venv\Lib\site-packages (3.2.0)
Requirement already satisfied: requests in D:\ml\.venv\Lib\site-packages (from pycoingecko) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in D:\ml\.venv\Lib\site-packages (from requests->pycoingecko) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in D:\ml\.venv\Lib\site-packages (from requests->pycoingecko) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in D:\ml\.venv\Lib\site-packages (from requests->pycoingecko) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in D:\ml\.venv\Lib\site-packages (from requests->pycoingecko) (2026.1.4)

In [45]:
from pycoingecko import CoinGeckoAPI

In [46]:
cg = CoinGeckoAPI() #tạo 1 object kết nói với máy chủ (như ng đại diện để đưa ra request)

price = cg.get_price(ids='bitcoin', vs_currencies='usd') #gửi 1 request (get_price) cho cg để cg gửi tới máy chủ
# sau đó máy chủ gửi lại két quả (data - dictionary)

price

{'bitcoin': {'usd': 69888}}

In [47]:
bitcoin_data = cg.get_coin_market_chart_by_id(id = 'bitcoin', vs_currency = 'usd', days=30)

In [48]:
bitcoin_data

{'prices': [[1770559445266, 71450.09750719942],
  [1770563015083, 71185.43635252847],
  [1770566650149, 71093.28992022508],
  [1770570234244, 70382.8443423587],
  [1770573844287, 70734.71298641211],
  [1770577440230, 71115.10260731545],
  [1770581039582, 71364.02621667292],
  [1770584415342, 70744.26363456192],
  [1770588224885, 70676.40743565756],
  [1770591793326, 71010.30811854756],
  [1770595437580, 70288.14411281867],
  [1770599050666, 70459.16182303062],
  [1770602544784, 70331.36328987485],
  [1770606161743, 70569.9975377267],
  [1770609818368, 71229.73530963564],
  [1770613390803, 70964.73659393784],
  [1770617070965, 70917.7140775821],
  [1770620577857, 70599.48065506382],
  [1770624214806, 70373.24121786421],
  [1770627915874, 69837.07732988766],
  [1770631464242, 69550.37698573632],
  [1770634990367, 68682.80182170549],
  [1770638648041, 68832.02582910914],
  [1770642178390, 69082.02289196198],
  [1770645818510, 68592.05509846479],
  [1770649437354, 69277.24182643309],
  [1770653048338, 69497.9504768076],
  [1770656658213, 70052.90697154785],
  [1770660278179, 70580.77336767624],
  [1770663827055, 70345.99548691839],
  [1770667423251, 70891.58132530384],
  [1770671058216, 70744.7606123553],
  [1770674613561, 70375.09590515462],
  [1770678229473, 70339.16694175807],
  [1770681843099, 70123.68796096664],
  [1770685432077, 69826.11877692133],
  [1770689048786, 70394.23922233515],
  [1770692601270, 70064.76056999435],
  [1770696179597, 69457.98618467282],
  [1770699777463, 69797.42294899575],
  [1770703382631, 69382.33864852159],
  [1770707009853, 68847.05069249081],
  [1770710543150, 68881.0732316969],
  [1770714186243, 69064.99112489945],
  [1770717837962, 69105.54398342568],
  [1770721344171, 68877.64853072929],
  [1770725020193, 68522.82784238047],
  [1770728579479, 68543.23050244208],
  [1770732168078, 68958.60997610839],
  [1770735744965, 68400.9302576248],
  [1770739381918, 69246.28467257677],
  [1770743001020, 69539.89537574978],
  [1770746597790, 69855.81229514664],
  [1770750151070, 68892.14110177293],
  [1770753791756, 69014.0978254628],
  [1770757242181, 68756.11136655635],
  [1770760998773, 68636.08258362056],
  [1770764590009, 68661.02296853696],
  [1770768270101, 68787.11157131186],
  [1770771778705, 69163.88217016484],
  [1770775395302, 68946.97762062182],
  [1770778822849, 68644.96060706391],
  [1770782518507, 68175.45041937327],
  [1770786239711, 67551.3977776452],
  [1770789788390, 67393.1338876921],
  [1770793394850, 66764.58898080258],
  [1770796857540, 67017.05721590634],
  [1770800640815, 66970.62905077402],
  [1770804222338, 66807.6119388558],
  [1770807649109, 66494.98120901024],
  [1770811466669, 67014.71498124763],
  [1770814941146, 67091.50719892021],
  [1770818634080, 67437.24255140442],
  [1770822142598, 66520.47043126007],
  [1770825818982, 66493.85891764812],
  [1770829377563, 66001.27448137071],
  [1770833032060, 66499.01615547431],
  [1770836574817, 67229.70574812587],
  [1770840145507, 67537.2135009556],
  [1770843613247, 67486.51819881125],
  [1770847391661, 67779.27675800232],
  [1770850977001, 67390.92632777932],
  [1770854594816, 66993.76514615967],
  [1770858210969, 67451.07122442544],
  [1770861740907, 67649.64782221185],
  [1770865333033, 67387.85725544306],
  [1770868959653, 67524.26768392987],
  [1770872445953, 66986.30434164265],
  [1770876187764, 67078.87774531855],
  [1770879753276, 67053.22272636107],
  [1770883386608, 67178.4581077123],
  [1770886826396, 67025.73999197627],
  [1770890594264, 67505.20239437708],
  [1770894152327, 67918.8668330455],
  [1770897797199, 68104.64609334413],
  [1770901404804, 67821.82074131482],
  [1770904945455, 68308.5139267418],
  [1770908560906, 67619.70970025606],
  [1770912140668, 67107.39876003392],
  [1770915800830, 65788.29080024328],
  [1770919336279, 65411.62913430127],
  [1770923004539, 65536.35172344626],
  [1770926443822, 65787.26041698357],
  [1770930044970, 65373.153465460666],
  [1770933720672, 65760.26221328336],
  [1770937300131, 66246.03819951249],
  [1770940963643, 66192.37908688825],
  [1770944584364, 65907.85178274351],
  [1770948160046, 66354.20379582758],
  [1770951622916, 66660.74922526913],
  [1770955364083, 66460.80346947702],
  [1770959002630, 66287.2478700668],
  [1770962612338, 66145.26647622047],
  [1770966224946, 66319.79278508217],
  [1770969649134, 66168.09118045383],
  [1770973404328, 66633.60165762658],
  [1770976873183, 66895.3374846119],
  [1770980554662, 66928.08718593771],
  [1770984109205, 67126.01455622054],
  [1770987760617, 67051.53066547718],
  [1770991333464, 67252.78657169837],
  [1770994934383, 67680.10358293349],
  [1770998400271, 68601.35608327099],
  [1771002000793, 69105.3880728048],
  [1771005613595, 69016.92320744746],
  [1771009294480, 69097.83747759652],
  [1771012983748, 68928.36804915236],
  [1771016607968, 68733.84411753804],
  [1771020223321, 68842.4853080273],
  [1771023750239, 68930.85615649213],
  [1771027335076, 68848.91601457071],
  [1771030958064, 69052.11814104643],
  [1771034491662, 68925.81413527165],
  [1771038083799, 68850.55795334087],
  [1771041752219, 68946.54151316333],
  [1771045409194, 68759.15934178799],
  [1771048977673, 68742.18544956709],
  [1771052442384, 68897.33349196923],
  [1771056180778, 69189.82934923672],
  [1771059645397, 69726.25267790715],
  [1771063296364, 69691.52126791891],
  [1771067003061, 69635.27468433385],
  [1771070448924, 70434.28463415819],
  [1771074228660, 69633.0263652205],
  [1771077785751, 69416.53585336605],
  [1771081389174, 69702.71797144218],
  [1771084981553, 69761.73770486697],
  [1771088576652, 69709.11375885298],
  [1771092191441, 69687.28327880825],
  [1771095760114, 69733.54122326875],
  [1771099362490, 69825.50119312223],
  [1771102968961, 69990.8175307309],
  [1771106639163, 69884.50659515375],
  [1771110176125, 69924.91653176714],
  [1771113833822, 69774.2353259966],
  [1771117406838, 69729.48913093255],
  [1771121007924, 69674.4394979836],
  [1771124576910, 69463.07617718862],
  [1771128252938, 69961.3128035441],
  [1771131807845, 70155.37241359024],
  [1771135373187, 70243.08860355157],
  [1771139033261, 70373.12694780517],
  [1771142564187, 70786.26660662086],
  [1771146229234, 70411.32054067256],
  [1771149770020, 70376.88960841866],
  [1771153396261, 70404.94823152284],
  [1771156982331, 70267.17175907342],
  [1771160650361, 69387.60144625134],
  [1771164204829, 68940.40544020956],
  [1771167820327, 69110.93706350432],
  [1771171405270, 69060.54773085675],
  [1771174957916, 69004.9733197395],
  [1771178557233, 68580.5740698471],
  [1771182032737, 68391.51912497477],
  [1771185778384, 68282.55660712713],
  [1771189399174, 68418.56410917995],
  [1771192956165, 68837.65412375923],
  [1771196554604, 68923.26011623367],
  [1771200111693, 68781.29710864896],
  [1771203746273, 68807.54988540319],
  [1771207347636, 68600.88251203044],
  [1771210940011, 68299.08789823233],
  [1771214507482, 68378.05073894249],
  [1771218137250, 68833.3771011827],
  [1771221684553, 68368.57404069978],
  [1771225393191, 68411.1284780013],
  [1771228973131, 68543.04733752139],
  [1771232505102, 68726.37761691494],
  [1771236183125, 68939.5890405427],
  [1771239759271, 68766.4623978235],
  [1771243347089, 68817.00684590373],
  [1771246949167, 69720.91528212125],
  [1771250562123, 68361.14702019827],
  [1771254222183, 68381.76268962049],
  [1771257777265, 67513.43201399366],
  [1771261368139, 67830.48266944081],
  [1771264957493, 67923.40204674947],
  [1771268638387, 67845.65549273694],
  [1771272200491, 67881.7978501668],
  [1771275806309, 68479.96365635042],
  [1771279428549, 68804.97684090007],
  [1771282976121, 68589.22180875255],
  [1771286610055, 68852.48637282102],
  [1771290135223, 68856.54508076754],
  [1771293756279, 68587.90136643896],
  [1771297416425, 68815.02905097854],
  [1771300931916, 68465.88015024242],
  [1771304442446, 68419.78749680043],
  [1771308045069, 68196.19133548804],
  [1771311843279, 68358.38868471434],
  [1771315320124, 68358.54885195654],
  [1771318921710, 68142.87710761404],
  [1771322515931, 68079.29361360389],
  [1771326135716, 67784.02666527066],
  [1771329632329, 67833.14545257023],
  [1771333338178, 67888.17582537961],
  [1771336833831, 68091.7970259687],
  [1771340551408, 66900.86088977731],
  [1771344147028, 67352.03557682618],
  [1771347638300, 67520.45663312795],
  [1771351365274, 67198.53776740881],
  [1771355000349, 68070.65432562269],
  [1771358465001, 67789.9677181016],
  [1771362132834, 67729.879969294],
  [1771365790689, 67643.96687622776],
  [1771369358968, 67511.08100510074],
  [1771372923508, 67478.66920269319],
  [1771376536416, 67295.93918777717],
  [1771380112564, 67121.17416691722],
  [1771383705436, 67298.87495580375],
  [1771387403314, 67605.87435157233],
  [1771390906523, 67770.52548526973],
  [1771394432154, 67610.24909276767],
  [1771398146424, 67812.32340573036],
  [1771401775802, 68087.77007418862],
  [1771405272191, 68092.30939990666],
  [1771409002928, 68130.76658086086],
  [1771412556503, 67757.18921579409],
  [1771416141509, 67378.80486981728],
  [1771419728004, 67465.52794094842],
  [1771423334250, 67191.89205610077],
  [1771426909221, 67156.67569324691],
  [1771430539135, 67663.21696845596],
  [1771434044658, 67105.62639714318],
  [1771437695746, 67147.92942211787],
  [1771441225557, 66315.35717122022],
  [1771444921312, 66143.11023952397],
  [1771448523574, 66245.54294126258],
  [1771452106007, 66319.09854121489],
  [1771455683232, 66395.02300417775],
  [1771459273233, 66437.13592509933],
  [1771462998732, 66422.48277202653],
  [1771466560008, 66833.17282840105],
  [1771470044709, 66822.55646014048],
  [1771473641661, 66933.92747646493],
  [1771477398157, 66780.89118616698],
  [1771480862769, 66837.42029796186],
  [1771484461425, 67116.50346018281],
  [1771488115418, 67170.02189428693],
  [1771491743652, 66935.07201032821],
  [1771495362686, 66811.14558678101],
  [1771498965150, 66808.56146870888],
  [1771502561805, 66477.69591909723],
  [1771506053718, 66493.38343507201],
  [1771509727060, 65893.78142463525],
  [1771513268233, 66395.49662413551],
  [1771516862850, 66361.8367706384],
  [1771520520239, 66301.02313033368],
  [1771524117321, 66299.1689966471],
  [1771527735671, 66982.72221505808],
  [1771531239949, 67011.6707462627],
  [1771535002401, 67091.72571178003],
  [1771538527434, 66898.79302429323],
  [1771542204375, 66915.1097813609],
  [1771545756225, 66956.66409601258],
  [1771549352687, 67227.67488249822],
  [1771552946623, 67247.43012565825],
  [1771556529439, 67239.57495785308],
  [1771560167556, 67334.82652058548],
  [1771563824628, 67232.6875433637],
  [1771567421193, 67767.35955427619],
  [1771570806770, 67839.84481085645],
  [1771574619701, 67806.37469278977],
  [1771578175707, 67850.71900445792],
  [1771581718021, 68172.85620895511],
  [1771585363278, 67910.89892947351],
  [1771588948194, 67346.76441904357],
  [1771592588447, 67502.25731074518],
  [1771596135266, 66754.63539163572],
  [1771599807650, 67101.97572410556],
  [1771603405167, 67558.75301277851],
  [1771606867292, 67782.28579901981],
  [1771610556353, 67582.50451035672],
  [1771614146779, 67920.91594116506],
  [1771617799390, 67622.66814335548],
  [1771621376127, 67700.63320434374],
  [1771624809080, 67774.4148817248],
  [1771628509104, 68041.9989547035],
  [1771632095614, 68001.16900641973],
  [1771635686318, 67814.84736860167],
  [1771639346125, 67938.11806652314],
  [1771642821704, 67990.97108159284],
  [1771646565685, 67636.09802439428],
  [1771650126973, 67795.1935276166],
  [1771653727329, 67833.35816343532],
  [1771657241289, 67771.15490900952],
  [1771660951186, 67835.58161535914],
  [1771664538042, 68033.45506604825],
  [1771668152943, 68134.27481021718],
  [1771671730600, 68185.96157291178],
  [1771675340281, 68080.98290497396],
  [1771678846188, 68177.9654336213],
  [1771682540586, 68234.65912706646],
  [1771686115506, 68447.8539525863],
  [1771689674798, 68624.35686959434],
  [1771693392362, 68302.62450497187],
  [1771696944648, 68404.98992152564],
  [1771700623634, 68560.684656393],
  [1771704234370, 68519.98114654892],
  [1771707796046, 68284.76941071317],
  [1771711361418, 68352.67780821405],
  [1771715005336, 67951.15591282771],
  [1771718528172, 67978.79019389286],
  [1771722031466, 67894.39819865709],
  [1771725727786, 68113.19039347471],
  [1771729346272, 67883.45039283701],
  [1771732924682, 68008.42174669018],
  [1771736570149, 67960.92293554958],
  [1771740189438, 67946.0233073144],
  [1771743741131, 68026.51169714678],
  [1771747419719, 67985.83510142777],
  [1771750922518, 67950.31445098891],
  [1771754555532, 68039.3698178956],
  [1771758128739, 68119.230120068],
  [1771761793668, 68194.59339383944],
  [1771765360756, 67931.58019160847],
  [1771768949467, 67631.9324739407],
  [1771772561726, 67417.69362212557],
  [1771776171675, 67664.896296285],
  [1771779728771, 67607.70037223128],
  [1771783354862, 67338.17491674826],
  [1771786946046, 67408.00208323984],
  [1771790582538, 67401.27120317247],
  [1771794180332, 67368.4929540634],
  [1771797753305, 67584.46138307691],
  [1771801360889, 67654.03558297858],
  [1771804813999, 67585.11718938159],
  [1771808545581, 66754.4877270225],
  [1771812202673, 64435.12705551635],
  [1771815789168, 64758.93071258205],
  [1771819338792, 64939.82443268619],
  [1771822978408, 64795.05744679692],
  [1771826555984, 65040.40875534817],
  [1771830236446, 65752.54244262996],
  [1771833723814, 65939.88775861052],
  [1771837401335, 65671.16025084569],
  [1771840934214, 66381.48055124872],
  [1771844584905, 66317.29222461591],
  [1771848130689, 66183.35606348574],
  [1771851744548, 66275.63595867298],
  [1771855330812, 66136.6157746477],
  [1771858955665, 65914.2830987351],
  [1771862602390, 65646.15558685549],
  [1771866236043, 65381.72366003015],
  [1771869776115, 64750.319959430264],
  [1771873401655, 64632.91383942887],
  [1771876883445, 64312.31488359545],
  [1771880604441, 64473.326092497344],
  [1771884188425, 64570.139420745654],
  [1771887757277, 64719.44720467718],
  [1771891378046, 64645.635433153606],
  [1771894815226, 64941.5287413215],
  [1771898591867, 64135.616801814576],
  [1771902171785, 64066.17992962856],
  [1771905753196, 63559.99285358071],
  [1771909412574, 63327.54954418396],
  [1771912956035, 63069.34251318558],
  [1771916527208, 63048.93669447095],
  [1771920143672, 63149.620867737],
  [1771923798129, 63379.60392637089],
  [1771927253541, 63219.563714987955],
  [1771930995131, 63276.255707804885],
  [1771934614966, 63207.59348187299],
  [1771938134798, 62972.76745130099],
  [1771941766857, 62905.750100773046],
  [1771945350514, 63446.927824582344],
  [1771948919734, 63963.04834579783],
  [1771952621260, 64253.8473670592],
  [1771956151983, 64215.262528875006],
  [1771959730148, 64426.94609155057],
  [1771963326332, 64443.4962359175],
  [1771967009711, 64455.44615715053],
  [1771970574209, 64045.70828857544],
  [1771974162249, 64113.9657402143],
  [1771977613956, 64074.11098528222],
  [1771981299044, 64233.58561002521],
  [1771985025182, 65942.41944954704],
  [1771988626366, 65893.8901244172],
  [1771992168874, 65390.04483381127],
  [1771995706902, 65448.36336319303],
  [1771999329130, 64880.50598865606],
  [1772002931206, 64881.88467477487],
  [1772006498149, 65017.3242472759],
  [1772010155156, 65506.82624135998],
  [1772013755632, 65544.01337155416],
  [1772017361481, 65383.60659238269],
  [1772020989893, 65410.95710978954],
  [1772024590986, 66060.99245398513],
  [1772028127699, 66244.50816119192],
  [1772031781279, 66951.8483170153],
  [1772035377383, 67415.14686028346],
  [1772038981064, 68273.92644509776],
  [1772042488020, 68650.00332182567],
  [1772046226810, 69340.35897252934],
  [1772049774362, 69050.96317272843],
  [1772053365840, 69161.64065289382],
  [1772057025345, 68978.70175168476],
  [1772060582721, 68441.72145291104],
  [1772064202991, 67954.59317212048],
  [1772067676297, 68350.69340538714],
  [1772071378977, 68260.21173008643],
  [1772074972735, 68268.5928309609],
  [1772078556365, 68208.52535054173],
  [1772082024028, 68588.06560827991],
  [1772085747972, 68433.73102263549],
  [1772089370879, 68178.6307566451],
  [1772092945249, 67849.39051310069],
  [1772096582267, 67957.27845983938],
  [1772100191397, 68571.59879322391],
  [1772103721784, 68299.30055745928],
  [1772107219411, 68033.5795724743],
  [1772110956758, 68170.72135753337],
  [1772114456908, 67911.73073937466],
  [1772118156508, 67688.04676583402],
  [1772121769547, 67386.85704262121],
  [1772125397215, 66641.5855103991],
  [1772128987311, 66832.31646241288],
  [1772132549890, 67323.78812321286],
  [1772136187535, 67584.87840019423],
  [1772139767888, 67383.36102620805],
  [1772143336975, 67448.46646231266],
  [1772146983518, 67559.77818097749],
  [1772150453072, 67461.32949507894],
  [1772154250117, 67222.78947317986],
  [1772157800001, 67347.6530265583],
  [1772161264048, 67330.59246292546],
  [1772164997716, 67617.93798877213],
  [1772168559543, 67736.13847728852],
  [1772172214069, 67721.51397522389],
  [1772175780908, 67664.12864244104],
  [1772179403778, 67693.93539996963],
  [1772183011409, 67938.63876392743],
  [1772186628337, 67368.86769274919],
  [1772190049932, 66633.33440506212],
  [1772193724991, 66137.85956271303],
  [1772197398856, 65904.75945603063],
  [1772201017476, 66256.92068837801],
  [1772204635943, 66063.82922104784],
  [1772208067904, 66113.3331187787],
  [1772211875419, 65521.390728947146],
  [1772215378562, 65695.35026055097],
  [1772218937533, 65299.540025783645],
  [1772222575766, 65405.874047720536],
  [1772226211780, 65588.53418897989],
  [1772229712876, 65517.64534439725],
  [1772233243964, 65612.79609265388],
  [1772236984104, 65878.83934363318],
  [1772240612868, 65941.42538516161],
  [1772244165866, 65808.00055297046],
  [1772247794211, 65966.53423583704],
  [1772251399760, 65788.14613409038],
  [1772254982782, 65662.79439577536],
  [1772258463629, 65537.09867487189],
  [1772262022635, 63176.9334493685],
  [1772265775584, 63810.10687487467],
  [1772269429539, 63476.500126458806],
  [1772272962145, 63657.71534599248],
  [1772276599574, 64006.60748905268],
  [1772280126101, 63861.75707587122],
  [1772283751240, 64003.684479422045],
  [1772287385069, 65140.35713333176],
  [1772290964040, 64469.59172637236],
  [1772294552582, 64855.35275953073],
  [1772298157785, 65106.72687684266],
  [1772301829262, 65397.729790718826],
  [1772305372916, 65917.05026344638],
  [1772308950300, 66356.50280967761],
  [1772312558306, 66944.88811985626],
  [1772316105360, 66745.27274458484],
  [1772319734866, 67185.74551060123],
  [1772323262109, 66995.18581485235],
  [1772326964572, 66809.96994970969],
  [1772330466920, 67268.51512364895],
  [1772334006114, 67767.30557255891],
  [1772337773315, 67526.95508425993],
  [1772341391535, 67350.74233063264],
  [1772345016389, 67320.54484543877],
  [1772348589751, 66933.9095543311],
  [1772352159784, 67136.87810167827],
  [1772355779808, 66557.00472800883],
  [1772359437243, 66428.74891325405],
  [1772362959590, 66467.91523335855],
  [1772366634113, 66464.75764364624],
  [1772370185193, 66321.46414426001],
  [1772373622380, 66978.00715223578],
  [1772377387065, 66862.50633139131],
  [1772380987684, 66912.03130812026],
  [1772384650532, 66114.20988441783],
  [1772388147294, 66026.83967860283],
  [1772391844817, 66317.29508274388],
  [1772395229771, 65958.59984228645],
  [1772398962601, 65315.30937987745],
  [1772402588164, 65704.60538102922],
  [1772406187390, 65226.85539035725],
  [1772409776203, 65736.20402056671],
  [1772413346429, 66524.74636770034],
  [1772416948670, 66537.9695482037],
  [1772420533716, 66291.94530434308],
  [1772424040985, 66827.45258916239],
  [1772427686540, 66794.89827984174],
  [1772431294853, 66737.66943353935],
  [1772434897239, 66204.54871028582],
  [1772438496706, 65967.07249157794],
  [1772442091166, 66248.42954464993],
  [1772445764134, 66178.75506689884],
  [1772449349321, 66264.51566776684],
  [1772452966025, 66338.31805946841],

In [49]:
bitcoin_data['prices']

[[1770559445266, 71450.09750719942],
 [1770563015083, 71185.43635252847],
 [1770566650149, 71093.28992022508],
 [1770570234244, 70382.8443423587],
 [1770573844287, 70734.71298641211],
 [1770577440230, 71115.10260731545],
 [1770581039582, 71364.02621667292],
 [1770584415342, 70744.26363456192],
 [1770588224885, 70676.40743565756],
 [1770591793326, 71010.30811854756],
 [1770595437580, 70288.14411281867],
 [1770599050666, 70459.16182303062],
 [1770602544784, 70331.36328987485],
 [1770606161743, 70569.9975377267],
 [1770609818368, 71229.73530963564],
 [1770613390803, 70964.73659393784],
 [1770617070965, 70917.7140775821],
 [1770620577857, 70599.48065506382],
 [1770624214806, 70373.24121786421],
 [1770627915874, 69837.07732988766],
 [1770631464242, 69550.37698573632],
 [1770634990367, 68682.80182170549],
 [1770638648041, 68832.02582910914],
 [1770642178390, 69082.02289196198],
 [1770645818510, 68592.05509846479],
 [1770649437354, 69277.24182643309],
 [1770653048338, 69497.9504768076],
 [1770656658213, 70052.90697154785],
 [1770660278179, 70580.77336767624],
 [1770663827055, 70345.99548691839],
 [1770667423251, 70891.58132530384],
 [1770671058216, 70744.7606123553],
 [1770674613561, 70375.09590515462],
 [1770678229473, 70339.16694175807],
 [1770681843099, 70123.68796096664],
 [1770685432077, 69826.11877692133],
 [1770689048786, 70394.23922233515],
 [1770692601270, 70064.76056999435],
 [1770696179597, 69457.98618467282],
 [1770699777463, 69797.42294899575],
 [1770703382631, 69382.33864852159],
 [1770707009853, 68847.05069249081],
 [1770710543150, 68881.0732316969],
 [1770714186243, 69064.99112489945],
 [1770717837962, 69105.54398342568],
 [1770721344171, 68877.64853072929],
 [1770725020193, 68522.82784238047],
 [1770728579479, 68543.23050244208],
 [1770732168078, 68958.60997610839],
 [1770735744965, 68400.9302576248],
 [1770739381918, 69246.28467257677],
 [1770743001020, 69539.89537574978],
 [1770746597790, 69855.81229514664],
 [1770750151070, 68892.14110177293],
 [1770753791756, 69014.0978254628],
 [1770757242181, 68756.11136655635],
 [1770760998773, 68636.08258362056],
 [1770764590009, 68661.02296853696],
 [1770768270101, 68787.11157131186],
 [1770771778705, 69163.88217016484],
 [1770775395302, 68946.97762062182],
 [1770778822849, 68644.96060706391],
 [1770782518507, 68175.45041937327],
 [1770786239711, 67551.3977776452],
 [1770789788390, 67393.1338876921],
 [1770793394850, 66764.58898080258],
 [1770796857540, 67017.05721590634],
 [1770800640815, 66970.62905077402],
 [1770804222338, 66807.6119388558],
 [1770807649109, 66494.98120901024],
 [1770811466669, 67014.71498124763],
 [1770814941146, 67091.50719892021],
 [1770818634080, 67437.24255140442],
 [1770822142598, 66520.47043126007],
 [1770825818982, 66493.85891764812],
 [1770829377563, 66001.27448137071],
 [1770833032060, 66499.01615547431],
 [1770836574817, 67229.70574812587],
 [1770840145507, 67537.2135009556],
 [1770843613247, 67486.51819881125],
 [1770847391661, 67779.27675800232],
 [1770850977001, 67390.92632777932],
 [1770854594816, 66993.76514615967],
 [1770858210969, 67451.07122442544],
 [1770861740907, 67649.64782221185],
 [1770865333033, 67387.85725544306],
 [1770868959653, 67524.26768392987],
 [1770872445953, 66986.30434164265],
 [1770876187764, 67078.87774531855],
 [1770879753276, 67053.22272636107],
 [1770883386608, 67178.4581077123],
 [1770886826396, 67025.73999197627],
 [1770890594264, 67505.20239437708],
 [1770894152327, 67918.8668330455],
 [1770897797199, 68104.64609334413],
 [1770901404804, 67821.82074131482],
 [1770904945455, 68308.5139267418],
 [1770908560906, 67619.70970025606],
 [1770912140668, 67107.39876003392],
 [1770915800830, 65788.29080024328],
 [1770919336279, 65411.62913430127],
 [1770923004539, 65536.35172344626],
 [1770926443822, 65787.26041698357],
 [1770930044970, 65373.153465460666],
 [1770933720672, 65760.26221328336],
 [1770937300131, 66246.03819951249],
 [1770940963643, 66192.37908688825],
 [1770944584364, 65907.85178274351],
 [1770948160046, 66354.20379582758],
 [1770951622916, 66660.74922526913],
 [1770955364083, 66460.80346947702],
 [1770959002630, 66287.2478700668],
 [1770962612338, 66145.26647622047],
 [1770966224946, 66319.79278508217],
 [1770969649134, 66168.09118045383],
 [1770973404328, 66633.60165762658],
 [1770976873183, 66895.3374846119],
 [1770980554662, 66928.08718593771],
 [1770984109205, 67126.01455622054],
 [1770987760617, 67051.53066547718],
 [1770991333464, 67252.78657169837],
 [1770994934383, 67680.10358293349],
 [1770998400271, 68601.35608327099],
 [1771002000793, 69105.3880728048],
 [1771005613595, 69016.92320744746],
 [1771009294480, 69097.83747759652],
 [1771012983748, 68928.36804915236],
 [1771016607968, 68733.84411753804],
 [1771020223321, 68842.4853080273],
 [1771023750239, 68930.85615649213],
 [1771027335076, 68848.91601457071],
 [1771030958064, 69052.11814104643],
 [1771034491662, 68925.81413527165],
 [1771038083799, 68850.55795334087],
 [1771041752219, 68946.54151316333],
 [1771045409194, 68759.15934178799],
 [1771048977673, 68742.18544956709],
 [1771052442384, 68897.33349196923],
 [1771056180778, 69189.82934923672],
 [1771059645397, 69726.25267790715],
 [1771063296364, 69691.52126791891],
 [1771067003061, 69635.27468433385],
 [1771070448924, 70434.28463415819],
 [1771074228660, 69633.0263652205],
 [1771077785751, 69416.53585336605],
 [1771081389174, 69702.71797144218],
 [1771084981553, 69761.73770486697],
 [1771088576652, 69709.11375885298],
 [1771092191441, 69687.28327880825],
 [1771095760114, 69733.54122326875],
 [1771099362490, 69825.50119312223],
 [1771102968961, 69990.8175307309],
 [1771106639163, 69884.50659515375],
 [1771110176125, 69924.91653176714],
 [1771113833822, 69774.2353259966],
 [1771117406838, 69729.48913093255],
 [1771121007924, 69674.4394979836],
 [1771124576910, 69463.07617718862],
 [1771128252938, 69961.3128035441],
 [1771131807845, 70155.37241359024],
 [1771135373187, 70243.08860355157],
 [1771139033261, 70373.12694780517],
 [1771142564187, 70786.26660662086],
 [1771146229234, 70411.32054067256],
 [1771149770020, 70376.88960841866],
 [1771153396261, 70404.94823152284],
 [1771156982331, 70267.17175907342],
 [1771160650361, 69387.60144625134],
 [1771164204829, 68940.40544020956],
 [1771167820327, 69110.93706350432],
 [1771171405270, 69060.54773085675],
 [1771174957916, 69004.9733197395],
 [1771178557233, 68580.5740698471],
 [1771182032737, 68391.51912497477],
 [1771185778384, 68282.55660712713],
 [1771189399174, 68418.56410917995],
 [1771192956165, 68837.65412375923],
 [1771196554604, 68923.26011623367],
 [1771200111693, 68781.29710864896],
 [1771203746273, 68807.54988540319],
 [1771207347636, 68600.88251203044],
 [1771210940011, 68299.08789823233],
 [1771214507482, 68378.05073894249],
 [1771218137250, 68833.3771011827],
 [1771221684553, 68368.57404069978],
 [1771225393191, 68411.1284780013],
 [1771228973131, 68543.04733752139],
 [1771232505102, 68726.37761691494],
 [1771236183125, 68939.5890405427],
 [1771239759271, 68766.4623978235],
 [1771243347089, 68817.00684590373],
 [1771246949167, 69720.91528212125],
 [1771250562123, 68361.14702019827],
 [1771254222183, 68381.76268962049],
 [1771257777265, 67513.43201399366],
 [1771261368139, 67830.48266944081],
 [1771264957493, 67923.40204674947],
 [1771268638387, 67845.65549273694],
 [1771272200491, 67881.7978501668],
 [1771275806309, 68479.96365635042],
 [1771279428549, 68804.97684090007],
 [1771282976121, 68589.22180875255],
 [1771286610055, 68852.48637282102],
 [1771290135223, 68856.54508076754],
 [1771293756279, 68587.90136643896],
 [1771297416425, 68815.02905097854],
 [1771300931916, 68465.88015024242],
 [1771304442446, 68419.78749680043],
 [1771308045069, 68196.19133548804],
 [1771311843279, 68358.38868471434],
 [1771315320124, 68358.54885195654],
 [1771318921710, 68142.87710761404],
 [1771322515931, 68079.29361360389],
 [1771326135716, 67784.02666527066],
 [1771329632329, 67833.14545257023],
 [1771333338178, 67888.17582537961],
 [1771336833831, 68091.7970259687],
 [1771340551408, 66900.86088977731],
 [1771344147028, 67352.03557682618],
 [1771347638300, 67520.45663312795],
 [1771351365274, 67198.53776740881],
 [1771355000349, 68070.65432562269],
 [1771358465001, 67789.9677181016],
 [1771362132834, 67729.879969294],
 [1771365790689, 67643.96687622776],
 [1771369358968, 67511.08100510074],
 [1771372923508, 67478.66920269319],
 [1771376536416, 67295.93918777717],
 [1771380112564, 67121.17416691722],
 [1771383705436, 67298.87495580375],
 [1771387403314, 67605.87435157233],
 [1771390906523, 67770.52548526973],
 [1771394432154, 67610.24909276767],
 [1771398146424, 67812.32340573036],
 [1771401775802, 68087.77007418862],
 [1771405272191, 68092.30939990666],
 [1771409002928, 68130.76658086086],
 [1771412556503, 67757.18921579409],
 [1771416141509, 67378.80486981728],
 [1771419728004, 67465.52794094842],
 [1771423334250, 67191.89205610077],
 [1771426909221, 67156.67569324691],
 [1771430539135, 67663.21696845596],
 [1771434044658, 67105.62639714318],
 [1771437695746, 67147.92942211787],
 [1771441225557, 66315.35717122022],
 [1771444921312, 66143.11023952397],
 [1771448523574, 66245.54294126258],
 [1771452106007, 66319.09854121489],
 [1771455683232, 66395.02300417775],
 [1771459273233, 66437.13592509933],
 [1771462998732, 66422.48277202653],
 [1771466560008, 66833.17282840105],
 [1771470044709, 66822.55646014048],
 [1771473641661, 66933.92747646493],
 [1771477398157, 66780.89118616698],
 [1771480862769, 66837.42029796186],
 [1771484461425, 67116.50346018281],
 [1771488115418, 67170.02189428693],
 [1771491743652, 66935.07201032821],
 [1771495362686, 66811.14558678101],
 [1771498965150, 66808.56146870888],
 [1771502561805, 66477.69591909723],
 [1771506053718, 66493.38343507201],
 [1771509727060, 65893.78142463525],
 [1771513268233, 66395.49662413551],
 [1771516862850, 66361.8367706384],
 [1771520520239, 66301.02313033368],
 [1771524117321, 66299.1689966471],
 [1771527735671, 66982.72221505808],
 [1771531239949, 67011.6707462627],
 [1771535002401, 67091.72571178003],
 [1771538527434, 66898.79302429323],
 [1771542204375, 66915.1097813609],
 [1771545756225, 66956.66409601258],
 [1771549352687, 67227.67488249822],
 [1771552946623, 67247.43012565825],
 [1771556529439, 67239.57495785308],
 [1771560167556, 67334.82652058548],
 [1771563824628, 67232.6875433637],
 [1771567421193, 67767.35955427619],
 [1771570806770, 67839.84481085645],
 [1771574619701, 67806.37469278977],
 [1771578175707, 67850.71900445792],
 [1771581718021, 68172.85620895511],
 [1771585363278, 67910.89892947351],
 [1771588948194, 67346.76441904357],
 [1771592588447, 67502.25731074518],
 [1771596135266, 66754.63539163572],
 [1771599807650, 67101.97572410556],
 [1771603405167, 67558.75301277851],
 [1771606867292, 67782.28579901981],
 [1771610556353, 67582.50451035672],
 [1771614146779, 67920.91594116506],
 [1771617799390, 67622.66814335548],
 [1771621376127, 67700.63320434374],
 [1771624809080, 67774.4148817248],
 [1771628509104, 68041.9989547035],
 [1771632095614, 68001.16900641973],
 [1771635686318, 67814.84736860167],
 [1771639346125, 67938.11806652314],
 [1771642821704, 67990.97108159284],
 [1771646565685, 67636.09802439428],
 [1771650126973, 67795.1935276166],
 [1771653727329, 67833.35816343532],
 [1771657241289, 67771.15490900952],
 [1771660951186, 67835.58161535914],
 [1771664538042, 68033.45506604825],
 [1771668152943, 68134.27481021718],
 [1771671730600, 68185.96157291178],
 [1771675340281, 68080.98290497396],
 [1771678846188, 68177.9654336213],
 [1771682540586, 68234.65912706646],
 [1771686115506, 68447.8539525863],
 [1771689674798, 68624.35686959434],
 [1771693392362, 68302.62450497187],
 [1771696944648, 68404.98992152564],
 [1771700623634, 68560.684656393],
 [1771704234370, 68519.98114654892],
 [1771707796046, 68284.76941071317],
 [1771711361418, 68352.67780821405],
 [1771715005336, 67951.15591282771],
 [1771718528172, 67978.79019389286],
 [1771722031466, 67894.39819865709],
 [1771725727786, 68113.19039347471],
 [1771729346272, 67883.45039283701],
 [1771732924682, 68008.42174669018],
 [1771736570149, 67960.92293554958],
 [1771740189438, 67946.0233073144],
 [1771743741131, 68026.51169714678],
 [1771747419719, 67985.83510142777],
 [1771750922518, 67950.31445098891],
 [1771754555532, 68039.3698178956],
 [1771758128739, 68119.230120068],
 [1771761793668, 68194.59339383944],
 [1771765360756, 67931.58019160847],
 [1771768949467, 67631.9324739407],
 [1771772561726, 67417.69362212557],
 [1771776171675, 67664.896296285],
 [1771779728771, 67607.70037223128],
 [1771783354862, 67338.17491674826],
 [1771786946046, 67408.00208323984],
 [1771790582538, 67401.27120317247],
 [1771794180332, 67368.4929540634],
 [1771797753305, 67584.46138307691],
 [1771801360889, 67654.03558297858],
 [1771804813999, 67585.11718938159],
 [1771808545581, 66754.4877270225],
 [1771812202673, 64435.12705551635],
 [1771815789168, 64758.93071258205],
 [1771819338792, 64939.82443268619],
 [1771822978408, 64795.05744679692],
 [1771826555984, 65040.40875534817],
 [1771830236446, 65752.54244262996],
 [1771833723814, 65939.88775861052],
 [1771837401335, 65671.16025084569],
 [1771840934214, 66381.48055124872],
 [1771844584905, 66317.29222461591],
 [1771848130689, 66183.35606348574],
 [1771851744548, 66275.63595867298],
 [1771855330812, 66136.6157746477],
 [1771858955665, 65914.2830987351],
 [1771862602390, 65646.15558685549],
 [1771866236043, 65381.72366003015],
 [1771869776115, 64750.319959430264],
 [1771873401655, 64632.91383942887],
 [1771876883445, 64312.31488359545],
 [1771880604441, 64473.326092497344],
 [1771884188425, 64570.139420745654],
 [1771887757277, 64719.44720467718],
 [1771891378046, 64645.635433153606],
 [1771894815226, 64941.5287413215],
 [1771898591867, 64135.616801814576],
 [1771902171785, 64066.17992962856],
 [1771905753196, 63559.99285358071],
 [1771909412574, 63327.54954418396],
 [1771912956035, 63069.34251318558],
 [1771916527208, 63048.93669447095],
 [1771920143672, 63149.620867737],
 [1771923798129, 63379.60392637089],
 [1771927253541, 63219.563714987955],
 [1771930995131, 63276.255707804885],
 [1771934614966, 63207.59348187299],
 [1771938134798, 62972.76745130099],
 [1771941766857, 62905.750100773046],
 [1771945350514, 63446.927824582344],
 [1771948919734, 63963.04834579783],
 [1771952621260, 64253.8473670592],
 [1771956151983, 64215.262528875006],
 [1771959730148, 64426.94609155057],
 [1771963326332, 64443.4962359175],
 [1771967009711, 64455.44615715053],
 [1771970574209, 64045.70828857544],
 [1771974162249, 64113.9657402143],
 [1771977613956, 64074.11098528222],
 [1771981299044, 64233.58561002521],
 [1771985025182, 65942.41944954704],
 [1771988626366, 65893.8901244172],
 [1771992168874, 65390.04483381127],
 [1771995706902, 65448.36336319303],
 [1771999329130, 64880.50598865606],
 [1772002931206, 64881.88467477487],
 [1772006498149, 65017.3242472759],
 [1772010155156, 65506.82624135998],
 [1772013755632, 65544.01337155416],
 [1772017361481, 65383.60659238269],
 [1772020989893, 65410.95710978954],
 [1772024590986, 66060.99245398513],
 [1772028127699, 66244.50816119192],
 [1772031781279, 66951.8483170153],
 [1772035377383, 67415.14686028346],
 [1772038981064, 68273.92644509776],
 [1772042488020, 68650.00332182567],
 [1772046226810, 69340.35897252934],
 [1772049774362, 69050.96317272843],
 [1772053365840, 69161.64065289382],
 [1772057025345, 68978.70175168476],
 [1772060582721, 68441.72145291104],
 [1772064202991, 67954.59317212048],
 [1772067676297, 68350.69340538714],
 [1772071378977, 68260.21173008643],
 [1772074972735, 68268.5928309609],
 [1772078556365, 68208.52535054173],
 [1772082024028, 68588.06560827991],
 [1772085747972, 68433.73102263549],
 [1772089370879, 68178.6307566451],
 [1772092945249, 67849.39051310069],
 [1772096582267, 67957.27845983938],
 [1772100191397, 68571.59879322391],
 [1772103721784, 68299.30055745928],
 [1772107219411, 68033.5795724743],
 [1772110956758, 68170.72135753337],
 [1772114456908, 67911.73073937466],
 [1772118156508, 67688.04676583402],
 [1772121769547, 67386.85704262121],
 [1772125397215, 66641.5855103991],
 [1772128987311, 66832.31646241288],
 [1772132549890, 67323.78812321286],
 [1772136187535, 67584.87840019423],
 [1772139767888, 67383.36102620805],
 [1772143336975, 67448.46646231266],
 [1772146983518, 67559.77818097749],
 [1772150453072, 67461.32949507894],
 [1772154250117, 67222.78947317986],
 [1772157800001, 67347.6530265583],
 [1772161264048, 67330.59246292546],
 [1772164997716, 67617.93798877213],
 [1772168559543, 67736.13847728852],
 [1772172214069, 67721.51397522389],
 [1772175780908, 67664.12864244104],
 [1772179403778, 67693.93539996963],
 [1772183011409, 67938.63876392743],
 [1772186628337, 67368.86769274919],
 [1772190049932, 66633.33440506212],
 [1772193724991, 66137.85956271303],
 [1772197398856, 65904.75945603063],
 [1772201017476, 66256.92068837801],
 [1772204635943, 66063.82922104784],
 [1772208067904, 66113.3331187787],
 [1772211875419, 65521.390728947146],
 [1772215378562, 65695.35026055097],
 [1772218937533, 65299.540025783645],
 [1772222575766, 65405.874047720536],
 [1772226211780, 65588.53418897989],
 [1772229712876, 65517.64534439725],
 [1772233243964, 65612.79609265388],
 [1772236984104, 65878.83934363318],
 [1772240612868, 65941.42538516161],
 [1772244165866, 65808.00055297046],
 [1772247794211, 65966.53423583704],
 [1772251399760, 65788.14613409038],
 [1772254982782, 65662.79439577536],
 [1772258463629, 65537.09867487189],
 [1772262022635, 63176.9334493685],
 [1772265775584, 63810.10687487467],
 [1772269429539, 63476.500126458806],
 [1772272962145, 63657.71534599248],
 [1772276599574, 64006.60748905268],
 [1772280126101, 63861.75707587122],
 [1772283751240, 64003.684479422045],
 [1772287385069, 65140.35713333176],
 [1772290964040, 64469.59172637236],
 [1772294552582, 64855.35275953073],
 [1772298157785, 65106.72687684266],
 [1772301829262, 65397.729790718826],
 [1772305372916, 65917.05026344638],
 [1772308950300, 66356.50280967761],
 [1772312558306, 66944.88811985626],
 [1772316105360, 66745.27274458484],
 [1772319734866, 67185.74551060123],
 [1772323262109, 66995.18581485235],
 [1772326964572, 66809.96994970969],
 [1772330466920, 67268.51512364895],
 [1772334006114, 67767.30557255891],
 [1772337773315, 67526.95508425993],
 [1772341391535, 67350.74233063264],
 [1772345016389, 67320.54484543877],
 [1772348589751, 66933.9095543311],
 [1772352159784, 67136.87810167827],
 [1772355779808, 66557.00472800883],
 [1772359437243, 66428.74891325405],
 [1772362959590, 66467.91523335855],
 [1772366634113, 66464.75764364624],
 [1772370185193, 66321.46414426001],
 [1772373622380, 66978.00715223578],
 [1772377387065, 66862.50633139131],
 [1772380987684, 66912.03130812026],
 [1772384650532, 66114.20988441783],
 [1772388147294, 66026.83967860283],
 [1772391844817, 66317.29508274388],
 [1772395229771, 65958.59984228645],
 [1772398962601, 65315.30937987745],
 [1772402588164, 65704.60538102922],
 [1772406187390, 65226.85539035725],
 [1772409776203, 65736.20402056671],
 [1772413346429, 66524.74636770034],
 [1772416948670, 66537.9695482037],
 [1772420533716, 66291.94530434308],
 [1772424040985, 66827.45258916239],
 [1772427686540, 66794.89827984174],
 [1772431294853, 66737.66943353935],
 [1772434897239, 66204.54871028582],
 [1772438496706, 65967.07249157794],
 [1772442091166, 66248.42954464993],
 [1772445764134, 66178.75506689884],
 [1772449349321, 66264.51566776684],
 [1772452966025, 66338.31805946841],
 [1772456549144, 65950.51931767022],
 [1772460216960, 65415.50558372273],
 [1772463688544, 67038.38245351319],
 [1772467390506, 69099.85502941068],
 [1772470970866, 69481.99623180542],
 [1772474575800, 69165.18178595224],
 [1772478168554, 68907.87703621876],
 [1772481794977, 68957.55414612222],
 [1772485276347, 69250.0451801749],
 [1772488998819, 69429.26854903967],
 [1772492577445, 69388.34462523523],
 [1772496223766, 68810.6953580863],
 [1772499638335, 69026.20614885502],
 [1772503043895, 68905.30304363774],
 [1772503402291, 68751.354331694],

In [50]:
import pandas as pd
data = pd.DataFrame(bitcoin_data['prices'], columns = ['TimeStamp','Price'])
data

         TimeStamp         Price
0    1770559445266  71450.097507
1    1770563015083  71185.436353
2    1770566650149  71093.289920
3    1770570234244  70382.844342
4    1770573844287  70734.712986
..             ...           ...
717  1773136943788  71056.899081
718  1773140561894  70770.463031
719  1773144182453  70612.084110
720  1773147789637  70533.414323
721  1773150433000  69936.718509

[722 rows x 2 columns]

In [51]:
data['Date'] = pd.to_datetime(data['TimeStamp'], unit = 'ms')
data

         TimeStamp         Price                    Date
0    1770559445266  71450.097507 2026-02-08 14:04:05.266
1    1770563015083  71185.436353 2026-02-08 15:03:35.083
2    1770566650149  71093.289920 2026-02-08 16:04:10.149
3    1770570234244  70382.844342 2026-02-08 17:03:54.244
4    1770573844287  70734.712986 2026-02-08 18:04:04.287
..             ...           ...                     ...
717  1773136943788  71056.899081 2026-03-10 10:02:23.788
718  1773140561894  70770.463031 2026-03-10 11:02:41.894
719  1773144182453  70612.084110 2026-03-10 12:03:02.453
720  1773147789637  70533.414323 2026-03-10 13:03:09.637
721  1773150433000  69936.718509 2026-03-10 13:47:13.000

[722 rows x 3 columns]

In [63]:
candlestick_data = data.groupby(data.Date.dt.date).agg({'Price': ['min','max','first','last']})
candlestick_data

                   Price
                     min           max         first          last
Date
2026-02-08  70382.844342  71450.097507  71450.097507  71010.308119
2026-02-09  68592.055098  71229.735310  70288.144113  70339.166942
2026-02-10  68400.930258  70394.239222  70123.687961  68661.022969
2026-02-11  66001.274481  69163.882170  68787.111571  67390.926328
2026-02-12  65373.153465  68308.513927  66993.765146  66246.038200
2026-02-13  65907.851783  69105.388073  66192.379087  68930.856156
2026-02-14  68742.185450  70434.284634  68848.916015  69924.916532
2026-02-15  68282.556607  70786.266607  69774.235326  68923.260116
2026-02-16  67513.432014  69720.915282  68781.297109  68589.221809
2026-02-17  66900.860890  68856.545081  68852.486373  67511.081005
2026-02-18  66143.110240  68130.766581  67478.669203  66395.023004
2026-02-19  65893.781425  67170.021894  66437.135925  66915.109781
2026-02-20  66754.635392  68172.856209  66956.664096  68041.998955
2026-02-21  67636.098024  68624.356870  68001.169006  67951.155913
2026-02-22  67338.174917  68194.593394  67978.790194  67654.035583
2026-02-23  64312.314884  67585.117189  67585.117189  64719.447205
2026-02-24  62905.750101  64941.528741  64645.635433  64113.965740
2026-02-25  64074.110985  69340.358973  64074.110985  68441.721453
2026-02-26  66641.585510  68588.065608  67954.593172  67559.778181
2026-02-27  65299.540026  67938.638764  67461.329495  65612.796093
2026-02-28  63176.933449  67185.745511  65878.839344  67185.745511
2026-03-01  65226.855390  67767.305573  66995.185815  65226.855390
2026-03-02  65415.505584  69481.996232  65736.204021  69388.344625
2026-03-03  66628.767749  69026.206149  68810.695358  68265.410758
2026-03-04  67727.150549  73669.778869  68292.192849  72719.814065
2026-03-05  70744.215997  73406.869889  72718.887891  71233.218712
2026-03-06  67974.712782  71240.535655  70878.272629  68413.332016
2026-03-07  67094.311995  68341.333957  68133.412344  67249.113592
2026-03-08  66243.611180  67884.756056  67267.812969  66243.611180
2026-03-09  65962.935558  69151.006378  65962.935558  68646.004299
2026-03-10  68420.966240  71056.899081  68420.966240  69936.718509

In [62]:
import plotly.graph_objects as go
fig = go.Figure(data=[go.Candlestick(x = candlestick_data.index,
        open = candlestick_data['Price']['first'],
        high = candlestick_data['Price']['max'],
        low = candlestick_data['Price']['min'],
        close = candlestick_data['Price']['last']
        )]
    )
fig.update_layout(xaxis_rangeslider_visible = False,
    xaxis_title = 'Date',
    yaxis_title = 'Price (USD $)',
    title = 'Bitcoin Candlestick Chart Over Past 30 Days')